BLACK = (0, 0, 0)
RED = (255,0 , 0)
WINDOW_WIDTH = 1000
WINDOW_HEIGHT = 600
WINDOW_SIZE = (WINDOW_HEIGHT, WINDOW_WIDTH)

FPS = (60)
PLAYER_WIDTH = 30
PLAYER_HEIGHT = 30
PLAYER_SIZE = (PLAYER_HEIGHT, PLAYER_WIDTH)

